spring.application.name=project
server.port=8080
management.endpoints.web.exposure.include=health,metrics,prometheus
management.metrics.export.graphite.host=host.docker.internal
management.metrics.export.graphite.port=2003
management.metrics.export.graphite.step=10s